name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo
          uses: actions/checkout@v4 

        - name: List and Read Files
          run: |
           echo "My first Github Actions Job"
           ls -ltra
           cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON...ROWR" >> dragon.txt

       # - name: read File
         # run: cat README.md
