name: multiple-workflows

on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON ... ROAR" >> dragon.txt

            - name: Upload Dragon text file
              uses: actions/upload-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt

    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 10 seconds
              run: sleep 0
            
            - name: Upload Dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file

    deploy_job3:
        needs: [test_job2, build_job1]
        runs-on: ubuntu-latest
        steps:
            - name: Upload Dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: deploying...

